# Application Name
spring.application.name=Order-Processing

# Server
server.port=8080

order.file.input=/input/orders
order.file.error=/error/orders

spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.persistent=false
spring.artemis.embedded.queues=ORDER.CREATED.QUEUE
spring.artemis.host=localhost
spring.artemis.port=61616

jwt.secret=cashinvoice_super_secret_key_2024_do_not_share_12345678901234567890
jwt.expiration=86400000

logging.level.com.cashinvoice=DEBUG
logging.level.org.apache.camel=INFO
logging.level.org.apache.activemq=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n